version: "3"
services:
  php:
    build: ./docker/php
    volumes: 
      - ./app:/app
    networks: 
      - web 
  web:
    image: "nginx:1.13.8-alpine"
    volumes:
      - ./app:/app
      - ./app/public:/app/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      - "80:80"
    networks: 
      - web 
  mysql:
    image: "mysql:5.7"
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:      
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
    networks:
      - web
  pma:
    image: "phpmyadmin/phpmyadmin:4.7"
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      restart: always
    networks: 
      - web 

networks: 
  web:
    driver: bridge